language: objective-c
osx_image: xcode8.2

env:
  - THEOS=theos

before_install:
  - brew update
  - brew install dpkg ldid
  - curl -s -f -L https://raw.github.com/r-plus/dotfiles/master/install_theos.sh | bash
  - pwd
  - ls

script:
  - make clean
  - make
